### ISSUE TITLE
BungeeCord bug

### ISSUE THREAD

**Issue by TheHolyException** [TheCBProject/WirelessRedstone#10]
I have a server network with a ModPack server on BungeeCord, and if I want to connect with the WirelessRedstone mod is in the BungeeCord console: "disconnected with: Invalid payload REGISTER!" I've already tried it with other BungeeCord versions and it did not work.

sorry for my bad english, i used Google translate xd

**Comment by covers1624** [comment]
I'm not entirely sure this is me, without any more information its hard to say. As this issue is ainchent, im going to close it, please try with 1.12.
