### ISSUE TITLE
Crash when going to the end

### ISSUE THREAD

**Issue by LocalBoomer** [TheCBProject/WirelessRedstone#12]
https://paste.dimdev.org/nirequxoku.mccrash

Seems to be an issue with handling the Wireless Redstone channels when going to the end?

happened while loading the end after going using a vanilla portal.

Minecraft: 1.12.2
Forge: 14.23.4.2756
CodeChicken Library: 3.2.1.351
WirelessRedstone-CBE: 2.3.1.29

**Comment by covers1624** [comment]
This looks like a race condition.. o boy..

**Comment by covers1624** [comment]
Pending approval on curse.
