### ISSUE TITLE
Crash while entering Galacticraft space stations

### ISSUE THREAD

**Issue by HydrogenC** [TheCBProject/WirelessRedstone#15]
I launched my rocket to a space station I've just created. While entering (before the scene appeared again), the game crashed. 
[crash-2019-01-20_11.39.08-server.txt](https://github.com/TheCBProject/WirelessRedstone/files/2776236/crash-2019-01-20_11.39.08-server.txt)

**Comment by covers1624** [comment]
I have added protection for this.
