### ISSUE TITLE
fix: cs_CZ, ru_RU lang files

### ISSUE THREAD

**Issue by SupinePandora43** [TheCBProject/WirelessRedstone#17]
i'm Russian and i have the "wi??reless ?nifer", "triangul??tor" , "ob??idia?? stick"(translate from Russian to English). i created PR with fixes for ru_RU.lang: https://github.com/TheCBProject/WirelessRedstone/pull/18

**Comment by SupinePandora43** [comment]
8 days, GUYS COME ON!!!

**Comment by covers1624** [comment]
We arent all glued to out github pages and have real life and motivation to battle with. Please be patient.
