### ISSUE TITLE
Mod not work

### ISSUE THREAD

**Issue by WenSiL** [TheCBProject/WirelessRedstone#19]
Hey. I downloaded the latest versions of wireless redstone, codechickenlib and forgemultipart and installed it all on minecraft 1.12.2, but the mod doesn't work.
![Безымянный](https://user-images.githubusercontent.com/24543933/59832891-47be4d00-9388-11e9-9354-ac8363f982ee.png)

**Comment by HaddockA** [comment]
How do you expect to get any help when you can't be bothered to explain what exactly doesn't work?

**Comment by gigabit101** [comment]
Redstone is only accepted via the bottom of the block (The red line) The same behaver also for the receiver

**Comment by WenSiL** [comment]
> How do you expect to get any help when you can't be bothered to explain what exactly doesn't work?
I think this is seen in the screenshot. I set the receiver and transmitter, set them to the same frequency, brought redstone to the transmitter, activated it, but absolutely nothing happens.

**Comment by WenSiL** [comment]
> Redstone is only accepted via the bottom of the block (The red line) The same behaver also for the receiver

Right? Not work. Even the sliders on the transmitter and receiver are off.
![Безымянный](https://user-images.githubusercontent.com/24543933/61290083-5d4f5700-a80e-11e9-8bb4-8dd5fbd5e8d9.png)

**Comment by KingLemming** [comment]
...are you just being intentionally daft at this point? The line needs to connect. You have them raised up a block. Obviously the redstone does not transmit that way - that is just vanilla mechanics.

**Comment by Morpheus1101** [comment]
In case you dont follow the words, here is a picture for you :D 

![2019-07-25_08 46 46](https://user-images.githubusercontent.com/10524952/61833833-efafc480-aeb8-11e9-81a9-683506913888.png)

**Comment by WenSiL** [comment]
Im stupid, sorry.
