### ISSUE TITLE
WR is creating a weird DIM whenever a new world is created

### ISSUE THREAD

**Issue by johnfriedrich** [TheCBProject/WirelessRedstone#2]
Hey,
whenever we are generating a new world, WirelessRedstone creates a new DIM.
(At least I guess it WR, as the folder only contains a RedstoneEther folder)
So it looks like that:
http://prntscr.com/elvorz
Content of these DIMs:
http://prntscr.com/elvpcw
Content of RedstoneEther folder:
http://prntscr.com/elvpha

Is that really neccessary? It makes stuff really messy.

Using:
WR-CBE-1.10.2-2.0.0.18-universal.jar

**Comment by covers1624** [comment]
WR generates the RedstoneEather folder in each dimensions folder. WR does not create actual dimensions that is another mod.
