### ISSUE TITLE
Two recipes?

### ISSUE THREAD

**Issue by xJon** [TheCBProject/WirelessRedstone#22]
Any idea why am I getting two identical recipes registered?
![Screenshot_5](https://user-images.githubusercontent.com/8945347/63407448-e4a47180-c42f-11e9-9e0f-719d1069f2c8.png)
They both have different IDs. 
Using `1.12.2-2.3.2.33`.

**Comment by covers1624** [comment]
They are not identical, one has the Restone and Glowstone rotated. This is not a bug.

**Comment by xJon** [comment]
Overlooked it, whoops. Thanks!
