### ISSUE TITLE
Crash Report [Unexpected error  java.lang.NullPointerException: Unexpected error]

### ISSUE THREAD

**Issue by Lightone** [TheCBProject/WirelessRedstone#3]
Click on the map any wireless map the game crash

[WR-CBE-1.10.2-2.0.0.18-universal]

<details>
  <summary>Click to expand Crash Log</summary>
  `---- Minecraft Crash Report ----

WARNING: coremods are present:
  IvToolkit (IvToolkit-1.2.8.4.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.65-beta.jar)
  SFRCore (SolarFluxReborn_1.10.2-2.6r.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.5.6.233-universal.jar)
  NEICorePlugin (NotEnoughItems-1.10.2-2.1.3.199-universal.jar)
  CamPatchingLoader (CMDCam v1.1.2 mc1.10.2.jar)
  ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.0.jar)
Contact their authors BEFORE contacting forge

// Oops.

Time: 19/03/17 09:51 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at net.minecraft.client.gui.MapItemRenderer.func_148248_b(SourceFile:39)
	at net.minecraft.client.gui.MapItemRenderer.func_148250_a(SourceFile:35)
	at codechicken.wirelessredstone.client.render.WirelessMapRenderer.renderMap(WirelessMapRenderer.java:142)
	at codechicken.lib.render.item.map.MapRenderRegistry.handleRender(MapRenderRegistry.java:34)
	at net.minecraft.client.renderer.ItemRenderer.func_187461_a(ItemRenderer.java)
	at net.minecraft.client.renderer.ItemRenderer.func_187463_a(ItemRenderer.java:225)
	at net.minecraft.client.renderer.ItemRenderer.func_187457_a(ItemRenderer.java:408)
	at net.minecraft.client.renderer.ItemRenderer.func_78440_a(ItemRenderer.java:365)
	at net.minecraft.client.renderer.EntityRenderer.renderHand(EntityRenderer.java:1037)
	at net.minecraft.client.renderer.EntityRenderer.func_78476_b(EntityRenderer.java:981)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1910)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1566)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1345)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.gui.MapItemRenderer.func_148248_b(SourceFile:39)
	at net.minecraft.client.gui.MapItemRenderer.func_148250_a(SourceFile:35)
	at codechicken.wirelessredstone.client.render.WirelessMapRenderer.renderMap(WirelessMapRenderer.java:142)
	at codechicken.lib.render.item.map.MapRenderRegistry.handleRender(MapRenderRegistry.java:34)
	at net.minecraft.client.renderer.ItemRenderer.func_187461_a(ItemRenderer.java)
	at net.minecraft.client.renderer.ItemRenderer.func_187463_a(ItemRenderer.java:225)
	at net.minecraft.client.renderer.ItemRenderer.func_187457_a(ItemRenderer.java:408)
	at net.minecraft.client.renderer.ItemRenderer.func_78440_a(ItemRenderer.java:365)
	at net.minecraft.client.renderer.EntityRenderer.renderHand(EntityRenderer.java:1037)
	at net.minecraft.client.renderer.EntityRenderer.func_78476_b(EntityRenderer.java:981)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1910)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1566)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Guartinajo'/278, l='MpServer', x=-99,49, y=64,00, z=-183,70]]
	Chunk stats: MultiplayerChunkCache: 121, 121
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-132,64,-144), Chunk: (at 12,4,0 in -9,-9; contains blocks -144,0,-144 to -129,255,-129), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 240196 game time, 1326275 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 23 total; [EntityBat['Bat'/192, l='MpServer', x=-110,25, y=55,10, z=-184,75], EntityFancyItemFrame['Golden Item Frame'/193, l='MpServer', x=-104,50, y=63,50, z=-162,97], EntityFancyItemFrame['Golden Item Frame'/194, l='MpServer', x=-103,50, y=63,50, z=-162,97], EntityFancyItemFrame['Golden Item Frame'/195, l='MpServer', x=-103,50, y=64,50, z=-162,97], EntityFancyItemFrame['Golden Item Frame'/196, l='MpServer', x=-104,50, y=64,50, z=-162,97], EntitySquid['Squid'/200, l='MpServer', x=-85,26, y=59,48, z=-243,87], EntitySquid['Squid'/206, l='MpServer', x=-75,85, y=52,41, z=-230,11], EntityBat['Bat'/208, l='MpServer', x=-80,25, y=19,10, z=-194,53], EntityBat['Bat'/209, l='MpServer', x=-77,44, y=17,12, z=-199,41], EntityPlayerSP['Guartinajo'/278, l='MpServer', x=-99,49, y=64,00, z=-183,70], EntityBat['Bat'/218, l='MpServer', x=-68,65, y=12,12, z=-209,25], EntityItem['item.item.leather'/156, l='MpServer', x=-156,49, y=60,00, z=-145,13], EntityItem['item.item.leather'/157, l='MpServer', x=-158,54, y=59,00, z=-147,91], EntityBat['Bat'/167, l='MpServer', x=-128,68, y=48,06, z=-160,32], EntitySquid['Squid'/174, l='MpServer', x=-116,96, y=61,08, z=-219,71], EntitySquid['Squid'/175, l='MpServer', x=-120,04, y=59,25, z=-210,93], EntityPig['Pig'/239, l='MpServer', x=-44,55, y=62,09, z=-157,78], EntitySquid['Squid'/177, l='MpServer', x=-126,54, y=56,00, z=-203,61], EntityBat['Bat'/178, l='MpServer', x=-117,75, y=60,10, z=-180,25], EntityBat['Bat'/179, l='MpServer', x=-118,63, y=52,57, z=-153,25], EntityBat['Bat'/189, l='MpServer', x=-110,25, y=55,10, z=-184,75], EntityBat['Bat'/190, l='MpServer', x=-110,40, y=57,10, z=-183,75], EntityBat['Bat'/191, l='MpServer', x=-110,25, y=55,10, z=-184,75]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:524)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:400)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 908705496 bytes (866 MB) / 1776816128 bytes (1694 MB) up to 2134114304 bytes (2035 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 1, tcache: 1, allocated: 12, tallocated: 94
	FML: MCP 9.32 Powered by Forge 12.18.3.2185 Optifine OptiFine_1.10.2_HD_U_D7 45 mods loaded, 45 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2185.jar) 
	UCHIJAAAA	Forge{12.18.3.2185} [Minecraft Forge] (forge-1.10.2-12.18.3.2185.jar) 
	UCHIJAAAA	cmdcam{0.2} [CMDCam] (minecraft.jar) 
	UCHIJAAAA	ivtoolkit{1.2.8.4} [IvToolkit] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{2.1.3.199} [Not Enough Items] (NotEnoughItems-1.10.2-2.1.3.199-universal.jar) 
	UCHIJAAAA	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.10.2-2.5.6.233-universal.jar) 
	UCHIJAAAA	base{1.10.2-1.2.4} [B.A.S.E] (base-1.10.2-1.2.4.jar) 
	UCHIJAAAA	BetterAchievements{0.3.0.30} [Better Achievements] (BetterAchievements-1.10.2-0.3.0.30.jar) 
	UCHIJAAAA	BlockDispenser{1.0} [BlockDispenser] (BlockDispenser-1.0-1.jar) 
	UCHIJAAAA	Chameleon{1.10-2.2.2} [Chameleon] (Chameleon-1.10-2.2.2.jar) 
	UCHIJAAAA	clumps{1.0.5} [Clumps] (Clumps-1.0.5.jar) 
	UCHIJAAAA	CodeChickenLib{2.5.6.233} [CodeChicken Lib] (CodeChickenLib-1.10.2-2.5.6.233-universal.jar) 
	UCHIJAAAA	CodeChickenCore{2.4.0.101} [CodeChicken Core] (CodeChickenCore-1.10.2-2.4.0.101-universal.jar) 
	UCHIJAAAA	coroutil{1.10.2-1.1.12} [CoroUtil Library] (coroutil-1.10.2-1.1.12.jar) 
	UCHIJAAAA	extendedrenderer{v1.0} [Extended Renderer] (coroutil-1.10.2-1.1.12.jar) 
	UCHIJAAAA	configmod{v1.0} [Extended Mod Config] (coroutil-1.10.2-1.1.12.jar) 
	UCHIJAAAA	endercore{1.10.2-0.4.1.65-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.65-beta.jar) 
	UCHIJAAAA	excore{1.6.2} [EXCore] (Excore-1.6.2-1.10.2.jar) 
	UCHIJAAAA	JEI{3.14.4.404} [Just Enough Items] (jei_1.10.2-3.14.4.404.jar) 
	UCHIJAAAA	forestry{5.2.17.362} [Forestry] (forestry_1.10.2-5.2.17.362.jar) 
	UCHIJAAAA	forgemultipartcbe{2.0.0.29} [Forge Multipart CBE] (ForgeMultipart-1.10.2-2.0.0.29-universal.jar) 
	UCHIJAAAA	microblockcbe{2.0.0.29} [Forge Microblocks] (ForgeMultipart-1.10.2-2.0.0.29-universal.jar) 
	UCHIJAAAA	minecraftmultipartcbe{2.0.0.29} [Minecraft Multipart Plugin] (ForgeMultipart-1.10.2-2.0.0.29-universal.jar) 
	UCHIJAAAA	shadowmc{3.4.8} [ShadowMC] (ShadowMC-1.10.2-3.4.8.jar) 
	UCHIJAAAA	Funnels{1.1.2} [Funnels] (Funnels-1.10.2-1.1.2.jar) 
	UCHIJAAAA	hammercore{1.2.3} [Hammer Core] (HammerCore_1.10.2-1.2.3.jar) 
	UCHIJAAAA	inventorysorter{0.10.5+46} [Simple Inventory sorting] (inventorysorter-1.10.2-0.10.5+46.jar) 
	UCHIJAAAA	jeresources{0.5.8.98} [Just Enough Resources] (JustEnoughResources-1.10.2-0.5.8.98.jar) 
	UCHIJAAAA	mantle{1.10.2-1.1.5.205} [Mantle] (Mantle-1.10.2-1.1.5.jar) 
	UCHIJAAAA	harvestcraft{1.9.4-1.10.2g} [Pam's HarvestCraft] (Pam's HarvestCraft 1.9.4-1.10.2h.jar) 
	UCHIJAAAA	pcb{1.5.0} [Portable Craft Bench] (portablecraftbench-1.10.2-1.5.0.jar) 
	UCHIJAAAA	possessed{1.0.0} [Possessed] (possessed-1.0.0.jar) 
	UCHIJAAAA	reccomplex{1.2.1} [Recurrent Complex] (RecurrentComplex-1.2.1.jar) 
	UCHIJAAAA	shetiphiancore{3.3.0} [ShetiPhian-Core] (shetiphiancore-1.10.0-3.3.0.jar) 
	UCHIJAAAA	SimpleLabels{0.0.1} [SimpleLabels] (simplelabels-1-10.2-0.0.3.jar) 
	UCHIJAAAA	snad{1.10.2-1.6.09.20a} [Snad] (Snad-1.10.2-1.6.09.20a.jar) 
	UCHIJAAAA	solarfluxreborn{2.6r} [Solar Flux Reborn] (SolarFluxReborn_1.10.2-2.6r.jar) 
	UCHIJAAAA	tconstruct{1.10.2-2.6.3.500} [Tinkers' Construct] (TConstruct-1.10.2-2.6.3.jar) 
	UCHIJAAAA	torohealthmod{1.10.2-1} [ToroHealth Damage Indicators] (torohealth-1.10.2-1.jar) 
	UCHIJAAAA	Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
	UCHIJAAAA	WailaHarvestability{1.1.7} [Waila Harvestability] (WailaHarvestability-mc1.10-1.1.7.jar) 
	UCHIJAAAA	icse{1.1.0.0} [I Can See Everything] (Wawla-1.10.2-2.3.0.203.jar) 
	UCHIJAAAA	wawla{2.3.0.202} [What Are We Looking At] (Wawla-1.10.2-2.3.0.203.jar) 
	UCHIJAAAA	wrcbe{2.0.0} [WirelessRedstone-CBE] (WR-CBE-1.10.2-2.0.0.18-universal.jar) 
	Loaded coremods (and transformers): 
IvToolkit (IvToolkit-1.2.8.4.jar)
  
EnderCorePlugin (EnderCore-1.10.2-0.4.1.65-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
SFRCore (SolarFluxReborn_1.10.2-2.6r.jar)
  com.mrdimka.solarfluxreborn.core.SFRSerializedTransformer
CCLCorePlugin (CodeChickenLib-1.10.2-2.5.6.233-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.CCL_ASMTransformer
NEICorePlugin (NotEnoughItems-1.10.2-2.1.3.199-universal.jar)
  codechicken.nei.asm.NEITransformer
CamPatchingLoader (CMDCam v1.1.2 mc1.10.2.jar)
  com.creativemd.cmdcam.transform.CamTransformer
ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.0.jar)
  shetiphian.core.asm.ClassTransformer
	GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.3304' Renderer: 'Intel(R) HD Graphics 4000'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- WailaIntegration (Enabled/Not Forced)

	NotEnoughItems Invalid Fingerprint Reports: 
	CodeChickenLib Invalid Fingerprint Reports: 
	CodeChickenCore Invalid Fingerprint Reports: 
	Launched Version: 1.10.2-forge1.10.2-12.18.3.2185
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 4000 GL version 4.0.0 - Build 10.18.10.3304, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	
</details>

**Comment by covers1624** [comment]
This has been guarded against.
