### ISSUE TITLE
Scorge

### ISSUE THREAD

**Issue by SlainMaster** [TheCBProject/WirelessRedstone#34]
scorge doesnt have a compatible 1.12.2 version it says on aternos

**Comment by covers1624** [comment]
Scorge is not required for 1.12.

**Comment by SlainMaster** [comment]
thanks

На вт, 31.08.2021 г. в 13:32 ч. covers1624 ***@***.***>
написа:

**Comment by SlainMaster** [comment]
does it need cb multipart?


На вт, 31.08.2021 г. в 13:39 ч. Slain_Мaster ***@***.***> написа:

**Comment by SlainMaster** [comment]
also i dont understand how to use it

**Comment by covers1624** [comment]
Yes, CBMultipart is required (The project on CurseForge was renamed from ForgeMultipart).

What exactly do you not understand about its usage? There are plenty of wiki articles around, including those on the FTBWiki for how to use WirelessRedstone. However, integration into ProjectIntelligence is planned.

**Comment by SlainMaster** [comment]
I dont understand how to connect it with redstone.When i tried to,it didnt
work
