### ISSUE TITLE
Crash when entering the world

### ISSUE THREAD

**Issue by gengyunmaster** [TheCBProject/WirelessRedstone#35]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  DCASMPlugin (HeatAndClimateLib_1.12.2-3.8.7.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-2.0.0-257-universal.jar)
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.8.1-core.jar)
  TransformerLoader (OpenComputers-MC1.12.2-1.7.5.192.jar)
  weaponlib (mw_2.0-0.4.6.2_mc1.12.2.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
  JechCore (JustEnoughCharacters-1.12.0-3.5.1.jar)
  CoreMod (Aroma1997Core-1.12.2-2.0.0.2.b167.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  LogisticsPipesCoreLoader (logisticspipes-0.10.4.7.jar)
Contact their authors BEFORE contacting forge

// I bet Cylons wouldn't have this problem.

Time: 3/26/22 8:49 AM
Description: Exception in server tick loop

java.lang.RuntimeException: java.io.IOException: 系统找不到指定的路径。
	at codechicken.wirelessredstone.manager.SaveManager.resetWorld(SaveManager.java:95)
	at codechicken.wirelessredstone.manager.RedstoneEtherServer.init(RedstoneEtherServer.java:28)
	at codechicken.wirelessredstone.manager.RedstoneEther.loadServerWorld(RedstoneEther.java:150)
	at codechicken.wirelessredstone.handler.WREventHandler.onWorldLoad(WREventHandler.java:42)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_696_WREventHandler_onWorldLoad_Load.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.optifine.reflect.Reflector.call(Reflector.java:976)
	at net.optifine.reflect.Reflector.postForgeBusEvent(Reflector.java:1251)
	at net.optifine.reflect.Reflector.postForgeBusEvent(Reflector.java:1237)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:151)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:233)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: 系统找不到指定的路径。
	at java.io.WinNTFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(Unknown Source)
	at codechicken.wirelessredstone.manager.SaveManager.resetWorld(SaveManager.java:77)
	... 17 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_281, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 8196006416 bytes (7816 MB) / 12884901888 bytes (12288 MB) up to 12884901888 bytes (12288 MB)
	JVM Flags: 12 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16m -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:-DontCompileHugeMethods -Xmn128m -Xmx12288m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 14, tcache: 0, allocated: 6, tallocated: 105
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 Optifine OptiFine_1.12.2_HD_U_G5 72 mods loaded, 71 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                    | Version                  | Source                                              | Signature                                |
	|:------ |:--------------------- |:------------------------ |:--------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft             | 1.12.2                   | minecraft.jar                                       | None                                     |
	| LCHIJA | mcp                   | 9.42                     | minecraft.jar                                       | None                                     |
	| LCHIJA | FML                   | 8.0.99.99                | forge-1.12.2-14.23.5.2860.jar                       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                 | 14.23.5.2860             | forge-1.12.2-14.23.5.2860.jar                       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | dcs_asm               | 2.1.0                    | minecraft.jar                                       | 4cd12b92959105443b7b694fffe0cea9ed004886 |
	| LCHIJA | jecharacters          | 1.12.0-3.5.1             | JustEnoughCharacters-1.12.0-3.5.1.jar               | None                                     |
	| LCHIJA | openmodscore          | 0.12.2                   | minecraft.jar                                       | None                                     |
	| LCHIJA | opencomputers|core    | 1.7.5.192                | minecraft.jar                                       | None                                     |
	| LCHIJA | libvulpes             | 0.4.2.-88                | LibVulpes-1.12.2-0.4.2-88-universal.jar             | None                                     |
	| LCHIJA | advancedrocketry      | 2.0.0.-257               | AdvancedRocketry-1.12.2-2.0.0-257-universal.jar     | None                                     |
	| LCHIJA | aroma1997core         | 2.0.0.2.b167             | Aroma1997Core-1.12.2-2.0.0.2.b167.jar               | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| LCHIJA | aroma1997sdimension   | 2.0.0.2.b97              | Aroma1997s-Dimensional-World-1.12.2-2.0.0.2.b97.jar | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| LCHIJA | aromabackup           | 3.0.0.0.b135             | AromaBackup-1.12.2-3.0.0.0.b135.jar                 | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| LCHIJA | aromabackuprecovery   | 3.0.0.0.b135             | AromaBackup-1.12.2-3.0.0.0.b135.jar                 | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| LCHIJA | codechickenlib        | 3.2.3.358                | CodeChickenLib-1.12.2-3.2.3.358-universal.jar       | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | avaritia              | 3.3.0                    | Avaritia-1.12.2-3.3.0.37-universal.jar              | None                                     |
	| LCHIJA | biomesoplenty         | 7.0.1.2445               | BiomesOPlenty-1.12.2-7.0.1.2445-universal.jar       | None                                     |
	| LCHIJA | redstoneflux          | 2.1.1                    | RedstoneFlux-1.12-2.1.1.1-universal.jar             | None                                     |
	| LCHIJA | brandonscore          | 2.4.20                   | BrandonsCore-1.12.2-2.4.20.162-universal.jar        | None                                     |
	| LCHIJA | buildcraftlib         | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                        | None                                     |
	| LCHIJA | buildcraftcore        | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                        | None                                     |
	| LCHIJA | buildcraftbuilders    | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                        | None                                     |
	| LCHIJA | buildcrafttransport   | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                        | None                                     |
	| LCHIJA | buildcraftsilicon     | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                        | None                                     |
	| LCHIJA | buildcraftenergy      | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                        | None                                     |
	| LCHIJA | jei                   | 4.16.1.302               | jei_1.12.2-4.16.1.302.jar                           | None                                     |
	| LCHIJA | forestry              | 5.8.2.422                | forestry_1.12.2-5.8.2.422.jar                       | None                                     |
	| LCHIJA | buildcraftcompat      | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                        | None                                     |
	| LCHIJA | buildcraftfactory     | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                        | None                                     |
	| LCHIJA | buildcraftrobotics    | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                        | None                                     |
	| LCHIJA | carrots               | 1.0.0b1                  | carrotslib-mc1.12.2-1.0.0b1.jar                     | None                                     |
	| LCHIJA | chickenchunks         | 2.4.2.74                 | ChickenChunks-1.12.2-2.4.2.74-universal.jar         | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | ctm                   | MC1.12.2-1.0.2.31        | CTM-MC1.12.2-1.0.2.31.jar                           | None                                     |
	| LCHIJA | chisel                | MC1.12.2-1.0.2.45        | Chisel-MC1.12.2-1.0.2.45.jar                        | None                                     |
	| LCHIJA | chiselsandbits        | 14.33                    | chiselsandbits-14.33.jar                            | None                                     |
	| LCHIJA | dcs_lib               | 3.8.7                    | HeatAndClimateLib_1.12.2-3.8.7.jar                  | 4cd12b92959105443b7b694fffe0cea9ed004886 |
	| LCHIJA | dcs_climate           | 3.8.14                   | HeatAndClimateMod_1.12.2-3.8.14.jar                 | 4cd12b92959105443b7b694fffe0cea9ed004886 |
	| LCHIJA | coffeework            | 1.2.9                    | coffeework-1.2.9.jar                                | None                                     |
	| LCHIJA | cookingforblockheads  | 6.5.0                    | CookingForBlockheads_1.12.2-6.5.0.jar               | None                                     |
	| LCHIJA | culinaryconstruct     | 1.3.4                    | culinaryconstruct-1.3.4.jar                         | 2484ef4d131fdc0dca0647aa21b7b944ddb935a1 |
	| LCHIJA | ptrmodellib           | 1.0.5                    | PTRLib-1.0.5.jar                                    | None                                     |
	| LCHIJA | props                 | 2.6.3.7                  | Decocraft-2.6.3.7_1.12.2.jar                        | None                                     |
	| LCHIJA | draconicevolution     | 2.3.28                   | Draconic-Evolution-1.12.2-2.3.28.354-universal.jar  | None                                     |
	| LCHIJA | enderstorage          | 2.4.6.137                | EnderStorage-1.12.2-2.4.6.137-universal.jar         | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | extrautils2           | 1.0                      | extrautils2-1.12-1.9.9.jar                          | None                                     |
	| LCHIJA | familiarfauna         | 1.0.11                   | FamiliarFauna-1.12.2-1.0.11.jar                     | None                                     |
	| LCHIJA | forgemultipartcbe     | 2.6.2.83                 | ForgeMultipart-1.12.2-2.6.2.83-universal.jar        | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | microblockcbe         | 2.6.2.83                 | ForgeMultipart-1.12.2-2.6.2.83-universal.jar        | None                                     |
	| LCHIJA | minecraftmultipartcbe | 2.6.2.83                 | ForgeMultipart-1.12.2-2.6.2.83-universal.jar        | None                                     |
	| LCHIJA | waila                 | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                         | None                                     |
	| LCHIJA | inventorytweaks       | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                            | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCHIJA | journeymap            | 1.12.2-5.7.1             | journeymap-1.12.2-5.7.1.jar                         | None                                     |
	| LCHIJA | logisticspipes        | 0.10.4.7                 | logisticspipes-0.10.4.7.jar                         | None                                     |
	| LCHIJA | lycanitesmobs         | 2.0.8.5 - MC 1.12.2      | lycanitesmobs-1.12.2-2.0.8.5.jar                    | None                                     |
	| LCHIJA | mw                    | 0.4.6.2                  | mw_2.0-0.4.6.2_mc1.12.2.jar                         | None                                     |
	| LCHIJA | nutrition             | 4.9.0                    | Nutrition-1.12.2-4.9.0.jar                          | None                                     |
	| LCHIJA | openmods              | 0.12.2                   | OpenModsLib-1.12.2-0.12.2.jar                       | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| LCHIJA | openblocks            | 1.8.1                    | OpenBlocks-1.12.2-1.8.1.jar                         | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| LCHIJA | opencomputers         | 1.7.5.192                | OpenComputers-MC1.12.2-1.7.5.192.jar                | None                                     |
	| LCHIJA | harvestcraft          | 1.12.2zb                 | Pam's+HarvestCraft+1.12.2zg.jar                     | None                                     |
	| LCHIJA | patchouli             | 1.0-23.6                 | Patchouli-1.0-23.6.jar                              | None                                     |
	| LCHIJA | pizzacraft            | 2.0.19                   | PizzaCraft-1.12.2-2.0.19.jar                        | None                                     |
	| LCHIJA | rustic                | 1.1.7                    | rustic-1.1.7.jar                                    | None                                     |
	| LCHIJA | saltmod               | 1.12.6.2                 | SaltyMod-1.12.2-1.12.6.2.jar                        | None                                     |
	| LCHIJA | kiwi                  | 0.5.3.32                 | Kiwi-1.12.2-0.5.3.32.jar                            | None                                     |
	| LCHIJA | cuisine               | 0.5.22-build929          | Cuisine-0.5.22-build929.jar                         | None                                     |
	| LCHIJA | vanillafoodpantry     | 4.3.1                    | vanillafoodpantry-mc1.12.2-4.3.1.jar                | None                                     |
	| LCHIJA | wailaharvestability   | 1.1.12                   | WailaHarvestability-mc1.12-1.1.12.jar               | None                                     |
	| LCHIJA | wrcbe                 | 2.3.2                    | WR-CBE-1.12.2-2.3.2.33-universal.jar                | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | xlfoodmod             | 1.12.2-1.9.2             | XL-Food-Mod-1.12.2-1.9.2.jar                        | None                                     |
	| LCHIJA | thebetweenlands       | 3.8.1                    | TheBetweenlands-3.8.1-universal.jar                 | 38067d6878811efb38b6a045521cfd80b9b60b38 |
	| UD     | advancedrocketrycore  | 1                        | minecraft.jar                                       | None                                     |

	Loaded coremods (and transformers): 
DCASMPlugin (HeatAndClimateLib_1.12.2-3.8.7.jar)
  defeatedcrow.hac.asm.DCMethodTransformer
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-2.0.0-257-universal.jar)
  zmaster587.advancedRocketry.asm.ClassTransformer
TheBetweenlandsLoadingPlugin (TheBetweenlands-3.8.1-core.jar)
  thebetweenlands.core.TheBetweenlandsClassTransformer
TransformerLoader (OpenComputers-MC1.12.2-1.7.5.192.jar)
  li.cil.oc.common.asm.ClassTransformer
weaponlib (mw_2.0-0.4.6.2_mc1.12.2.jar)
  com.vicmatskiv.weaponlib.core.WeaponlibClassTransformer
OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
  openmods.core.OpenModsClassTransformer
JechCore (JustEnoughCharacters-1.12.0-3.5.1.jar)
  me.towdium.jecharacters.core.JechClassTransformer
CoreMod (Aroma1997Core-1.12.2-2.0.0.2.b167.jar)
  
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  team.chisel.ctm.client.asm.CTMTransformer
LogisticsPipesCoreLoader (logisticspipes-0.10.4.7.jar)
  logisticspipes.asm.LogisticsClassTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:FINISHED],[player_render_hook:FINISHED],[horse_null_fix:FINISHED]
	Patchouli open book context: n/a
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12.2_HD_U_G5
	OptiFine Build: 20210124-142939
	Render Distance Chunks: 16
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.4.0 - Build 20.19.15.4624
	OpenGlRenderer: Intel(R) Iris(TM) Graphics 6100
	OpenGlVendor: Intel
	CpuCount: 4

**Comment by covers1624** [comment]
Unfortunately, 1.12.2 is not supported anymore.

I recommend restoring your world from a backup.
