### ISSUE TITLE
Client stuck at "Loading world" when booting singleplayer world

### ISSUE THREAD

**Issue by 016Nojr** [TheCBProject/WirelessRedstone#4]
I have played in a singleplayer world in FTB Beyond since the release, and today Wireless Redstone caused the client to get stuck at the "Loading World" stage and internally crashing acoording to the log.

Forge: 12.18.3.2254
CCC: 2.4.0.101
CCL: 2.5.6.233
WR-CBE: 2.0.0.18

Log: http://paste.feed-the-beast.com/view/raw/09932a28
Check when the clock is "6:47:47" right before it turns to "6:47:48"

**Comment by covers1624** [comment]
This must have been a fluke, if it hapens again open a new issue at https://github.com/TheCBProject/Feedback

**Comment by 016Nojr** [comment]
Roger
