### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by Tyrantin** [TheCBProject/WirelessRedstone#6]
[crash-2017-04-07_00.06.22-client.txt](https://github.com/TheCBProject/WirelessRedstone/files/904523/crash-2017-04-07_00.06.22-client.txt)

Works when Stand alone but not with any mods added.

**Comment by covers1624** [comment]
Take it to the feedback repo, https://github.com/TheCBProject/Feedback

**Comment by covers1624** [comment]
Infact this is a long standing matter overdrive issue, they fire events for a custom texture atlas that shouldnt fire events.
