### ISSUE TITLE
ModelBakery Error with Milk Bucket Item Texture (You read that right)

### ISSUE THREAD

**Issue by BlackHoleFox** [TheCBProject/WirelessRedstone#9]
I was building a MC modpack and kept getting crashes whenever the game would load the milk bucket item texture. I went through and re added every mod one by one only until I had them all in but WR CBE. When I added it, the game would crash due to aforementioned texture error. Without it, it would load just fine. I have the most up to date version of CodeChickenCore, CodeChickenLib, Forge Multipart, and Forge itself for version 1.10.2 Attached below is the crashlog.
[crash-2018-02-03_20.48.22-client.txt](https://github.com/TheCBProject/WirelessRedstone/files/1693097/crash-2018-02-03_20.48.22-client.txt)

**Comment by covers1624** [comment]
This is MFR, has been reported hundreds of times to them and is completely load order dependent, adding WR-CBE likely throws the load order so the crash appears. Either remove MFR and use IndustrialForgoing or remove it and wait for MFR to update.
